### ISSUE TITLE
Any interest in an experiment creating a pure Go Oracle driver?

### ISSUE THREAD

**Issue by MichaelS11** [mattn/go-oci8#216]
Thought it might be interesting to try to create a pure Go Oracle driver to just select simple data from a table. Any interest in trying that experiment?

**Comment by mattn** [comment]
Is it related on database/sql package?

**Comment by MichaelS11** [comment]
The pure Go Oracle driver would be using the database/sql package/framework.

**Comment by mattn** [comment]
Ah, non-CGO driver right? I don't know where we can see the protocol of Oracle.

**Comment by MichaelS11** [comment]
Yeah.

That is part of the fun, figuring it out :)

I think there is some information about it here and there, but do not think there is an official document about it.

https://blog.pythian.com/repost-oracle-protocol/

**Comment by MichaelS11** [comment]
If anyone does have an interest, please let me know. :)

**Comment by sergeilem** [comment]
Great idea.

**Comment by robinsoon** [comment]
**Oracle is not open source, and the company's strategic positioning determines that it can be a pure Go driver rather than a go driver. Let the market test whether Oracle can maintain its leading position in data storage technology in the future. Due to commercial licensing issues, open source drivers are not recommended, which may involve confidentiality.**

**Comment by sijms** [comment]
https://github.com/sijms/go-ora
