### ISSUE TITLE
Change LastInsertId to unsuported

### ISSUE THREAD

**Issue by MichaelS11** [mattn/go-oci8#296]
@mattn 

The Oracle rowid is 13 bytes but int64 is only 8 bits. I think we should change LastInsertId to unsupported. What do you think?

**Comment by mattn** [comment]
>The Oracle rowid is 13 bytes but int64 is only 8 bits.

What do you mean? 64bit?

**Comment by MichaelS11** [comment]
Meant to say 8 bytes. So the amount/size of the rowid data can not fit into int64 size of 8 bytes.

**Comment by cjbj** [comment]
FWIW the newer [UROWID](https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/Data-Types.html#GUID-E9F3AE1C-AA6D-4262-A15F-778833251361) could take up to [4000 bytes](https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/Data-Types.html#GUID-7B72E154-677A-4342-A1EA-C74C1EA928E6) in the DB, and may need up to 5267 bytes in the Oracle Client.

**Comment by mattn** [comment]
Value of LastInsertId from go-oci8 is a pointer to string not real value of Oracle rowid. So it is possible to hold 4000 bytes rowid. I did not think that go-oci 8 could handle the rowid of Oracle because type of LastInsertId is typed to int64. go-oci8 need to call two APIs to get real LastInsertId

https://github.com/mattn/go-oci8/blob/b0e38e039e839a22d147a8415fad2f4592fdd1d7/_example/lastinsertid/main.go#L63

**Comment by MichaelS11** [comment]
Ah, got it. Thank you
