### ISSUE TITLE
Saving in BLOB has broken

### ISSUE THREAD

**Issue by mdarkzar** [mattn/go-oci8#363]
In one of the latest versions of driver, when a picture or file that is more than 70 kilobytes is saved in a BLOB. It saves only a part of it.
Saving was tested both insertion and updating (with preliminary empty_blob ()).

Go Version: 1.13.4
Oracle DB Version: 11.2.0.3

There is no such problem in the goracle driver.

Original picture:
![original](https://user-images.githubusercontent.com/25960537/68272683-3dc28f80-0086-11ea-87e1-cd8a4870299d.jpeg)

After save in BLOB:
![broken](https://user-images.githubusercontent.com/25960537/68272684-3dc28f80-0086-11ea-8d03-b1626d8012de.jpeg)

**Comment by MichaelS11** [comment]
Please make sure you are on the latest version of go-oci8

https://github.com/mattn/go-oci8/issues/357

**Comment by mdarkzar** [comment]
> Please make sure you are on the latest version of go-oci8
> 
> #357

I am on the latest version. Updated via go get -u github.com/mattn/go-oci8
In topic #357 disscused a blob select problem, vice versa in my case.
I’ve checked the saved blob with sql developer and it showed that the blob was incomplete.

**Comment by harshal** [comment]
I think I ran into the same thing. Using a parameter value to write a large string to an NCLOB column was failing for me. It turns out that you cant write data longer than 65536 bytes currently. This is because we use OCIBindByName() function to bind values which only supports buffers this long. According to https://docs.oracle.com/database/121/LNOCI/oci16rel003.htm#LNOCI72805 OCIBindByName2() needs to be used to avoid this problem. I locally hacked in this change and my problems went away. It appears that OCIBindByName2() is only supported in more recent versions of OCI, so I don't know if a patch along these lines would be acceptable.

**Comment by MichaelS11** [comment]
Looking at how best to fix this. What is your insert query look like?

**Comment by harshal** [comment]
My queries are straightforward inserts and updates. Here is an example
```
s := struct {Id int, Svg string} {Id: some_id, Data: svg}
_, err := tx.NamedExec(`UPDATE svg_images SET raw_svg = :svg WHERE id=:id`, s)
```
Here raw_svg is an NCLOB column where I have to save some fragments of svg files which can sometimes become as large as a megabyte. This particular example uses NamedExec from sqlx. However, the same thing happens even without using it. I ran into this problem while porting some existing python code to golang.

**Comment by MichaelS11** [comment]
Should have a fix for insert/update here:

https://github.com/mattn/go-oci8/pull/364

Please test.

Named bind variables and/or PL/SQL areas of the code has not been changed so most likely will need to do another pass to fix them.

**Comment by harshal** [comment]
Yep, I tested that PR and can confirm that it solves my problems. Thank you!

**Comment by MichaelS11** [comment]
Are we good? Can this be closed?

**Comment by mdarkzar** [comment]
> Are we good? Can this be closed?

Yes, it works. I've tested. Everything works fine. Thank you very much.

**Comment by MichaelS11** [comment]
Welcome :)
