### ISSUE TITLE
How to user connection as SYS should be as SYSDBA or SYSOPER

### ISSUE THREAD

**Issue by feifeiwoye** [mattn/go-oci8#76]
I only have SYS users, but I don't know how to connect.

**Comment by ricsmania** [comment]
As far as I know it's not possible. I have checked the source and the function OciLogon() doesn't allow SYSDBA logon. I have also checked the other drivers Goracle and Rana and they also don't seem to allow it.

But are you sure you need to connect as SYSDBA? Does the application you are creating really need DBA privileges? If not, I would seriously advise against it, because it might become a huge security hole.

If you have the SYS password, you can create a basic user and use it to connect.
